# For Production
version: "3.8"
services:
    naze_server:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: abc/naze
        container_name: naze
        environment:
            REDIS_HOST: naze_redis
            REDIS_PORT: 6379
            NODE_ENV: production
            PORT: 4949
        ports:
            - "4949:4949"
        command: yarn start
        restart: always
        depends_on:
            - naze_redis
            - naze_db
    naze_redis: # <using redis>
        image: redis
        container_name: naze_cache
    naze_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root-pass
            MYSQL_DATABASE: naze
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db:
