# For Production
version: "3.8"
services:
    server:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: abc/naze
        container_name: naze
        ports:
            - "4000:4000"
        command: yarn start
        restart: always
        depends_on:
            - redis
    redis: # <using redis>
        image: redis
        container_name: naze_cache
        ports:
            - "6379:6379"
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root-pass
            MYSQL_DATABASE: naze
        ports:
            - "5050:3306"
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db:
